[workspace]
resolver = "2"
members = ["runner", "benches"]

[workspace.package]
edition = "2021"
version = "0.1.0"

[workspace.dependencies]
anyhow = "1"
cairo-args-runner = "1.0"
clap = { version = "4", features = ["derive"] }
lalrpop = "0.20"
lalrpop-util = { version = "0.20", features = ["lexer", "unicode"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
cairo-felt = "0.9"
cairo-lang-runner = "2.5.0"
cairo-lang-sierra = "2.5.0"
cairo-lang-utils = "2.5.0"
cairo-vm = "0.9.2"
itertools = "0.12.0"
thiserror = "1.0"
num-bigint = "0.4"
