[workspace]
resolver = "2"
members = ["runner"]

[workspace.package]
edition = "2021"
version = "0.1.0"

[workspace.dependencies]
anyhow = "1.0.79"
cairo-args-runner = "1.0.1"
cairo-proof-parser = { git = "https://github.com/cartridge-gg/cairo-proof-parser", tag = "v0.1.1" }
clap = { version = "4.5.0", features = ["derive"] }
num-bigint = "0.4.4"
