[workspace]
resolver = "2"
members = ["runner"]

[workspace.package]
edition = "2021"
version = "0.1.0"

[workspace.dependencies]
anyhow = "1"
cairo-args-runner = "1.0"
clap = { version = "4", features = ["derive"] }
lalrpop = "0.20"
lalrpop-util = { version = "0.20", features = ["lexer", "unicode"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
