name: Continuous Integration - proof verification tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  verify-proof:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        layout: ["dex", "recursive", "recursive_with_poseidon", "small", "starknet", "starknet_with_keccak"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup Scarb
        uses: software-mansion/setup-scarb@v1
      
      - name: Setup Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Build project
        run: scarb build --no-default-features --features=${{ matrix.layout }},keccak
      
      - name: Test project
        run: scarb test --no-default-features --features=${{ matrix.layout }},keccak
      
      - name: Run verification
        run: cargo run --bin runner -- target/dev/cairo_verifier.sierra.json < examples/proofs/${{ matrix.layout }}/example_proof.json
