name: Continuous Integration - tests

on:
  push:
  pull_request:

jobs:
  formatting-and-testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup Scarb
        uses: software-mansion/setup-scarb@v1
      
      - name: Format code
        run: scarb fmt --check

      - name: Checkout custom scarb
        uses: actions/checkout@v3
        with:
          repository: fmkra/scarb
      
      - name: Build custom scarb
        run: cargo build
        working-directory: scarb
      
      - name: Run tests
        run: ./scarb/target/debug/scarb test
        working-directory: $GITHUB_WORKSPACE